from pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
run pip install fschat -i https://mirrors.aliyun.com/pypi/simple/
# webui
run pip install gdown plotly -i https://mirrors.aliyun.com/pypi/simple/
# train
run apt-get update && apt-get install -y git g++
run pip install einops flash_attn -i https://mirrors.aliyun.com/pypi/simple/
