from pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime
run pip install fschat 
# webui
run pip install gdown plotly 
# train
run apt-get update && apt-get install -y git g++
run pip install einops flash_attn==1.0.2
